name: 'Arul & Associates'
favicon: null
layout_spectrum: 0.060931663727387786
typography_spectrum: 0.39741200883872807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#452c7d'
    - '#f6f6f6'
    - '#d4d2dd'
    - '#aea6c1'
    - '#8478a2'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.7301573052536696
  rhythmicContrast: 0.5
purpose: []
